name: ci-build-example

on:
  push:
    paths:
      - 'ci-build-example/**'
  pull_request:
    paths:
      - 'ci-build-example/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Build linux/amd64
        working-directory: ci-build-example
        run: GOOS=linux GOARCH=amd64 go build -o ci-build-example-linux-amd64

      - name: upload linux/amd64 build
        working-directory: ci-build-example
        env:
          SLR_SIKALABS_UPLOAD_BIN_ACCESS_KEY: ${{ secrets.SLR_SIKALABS_UPLOAD_BIN_ACCESS_KEY }}
          SLR_SIKALABS_UPLOAD_BIN_SECRET_KEY: ${{ secrets.SLR_SIKALABS_UPLOAD_BIN_SECRET_KEY }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/sikalabs/slr/master/install.sh | sudo sh
          slr sikalabs-upload-bin ci-build-example-linux-amd64
