name: ci-build-example

on:
  push:
    paths:
      - 'ci-build-example/**'
  pull_request:
    paths:
      - 'ci-build-example/**'

jobs:
  ci-build-example:
    uses: ./.github/workflows/_build-and-upload.yml
    with:
      module: ci-build-example
    secrets: inherit
