name: upload-sikalabs-bin

on:
  push:
    paths:
      - 'upload-sikalabs-bin/**'
  pull_request:
    paths:
      - 'upload-sikalabs-bin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Build linux/amd64
        working-directory: upload-sikalabs-bin
        run: GOOS=linux GOARCH=amd64 go build -o upload-sikalabs-bin-linux-amd64

      - name: upload linux/amd64 build
        working-directory: upload-sikalabs-bin
        env:
          SLR_SIKALABS_UPLOAD_BIN_ACCESS_KEY: ${{ secrets.SLR_SIKALABS_UPLOAD_BIN_ACCESS_KEY }}
          SLR_SIKALABS_UPLOAD_BIN_SECRET_KEY: ${{ secrets.SLR_SIKALABS_UPLOAD_BIN_SECRET_KEY }}
        run: |
          go install github.com/sikalabsx/go-scripts-test/upload-sikalabs-bin@b268f8f
          upload-sikalabs-bin upload-sikalabs-bin-linux-amd64
